name: Nightly Build

on:
  workflow_dispatch:
  schedule: # Every workday at the 2 P.M. (UTC) we run a scheduled nightly build
    - cron: "0 15 * * MON-FRI"

jobs:
  check-new-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create GITHUB_OUTPUT file
        run: echo "GITHUB_OUTPUT=$(pwd)/output.txt" >> $GITHUB_ENV

      - name: Check for new release
        id: check-release
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          node check-new-release.mjs

      - name: Read GITHUB_OUTPUT
        id: read-output
        run: |
          echo "::set-output name=isNewRelease::$(grep '^isNewRelease=' output.txt | cut -d= -f2)"
          echo "::set-output name=latestTag::$(grep '^latestTag=' output.txt | cut -d= -f2)"

      - name: Trigger build docker workflow
        if: steps.read-output.outputs.isNewRelease == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build Docker Images
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{"tag": "${{ steps.read-output.outputs.latestTag }}", "publish_tag": "${{ steps.read-output.outputs.latestTag }}"}'
