name: Nightly Build

on:
  workflow_dispatch:
  schedule: # Every workday at the 2 P.M. (UTC) we run a scheduled nightly build
    - cron: '0 15 * * MON-FRI'

jobs:
  check-new-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Check for new release
        id: check-release
        run: |
          node check-new-release.mjs
      
      - uses: ./.github/workflows/build-docker.yml
        if: steps.check-release.outputs.isNewRelease == 'true'
        with:
          tag: steps.check-release.outputs.latestTag
          publish_tag: steps.check-release.outputs.latestTag
